name: Deploy Infrastructure with Terraform

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.5.0

    - name: Set Azure credentials
      run: |
        echo "Setting up Azure credentials..."
      env:
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    - name: Terraform validate
      run: terraform validate

    - name: Terraform init
      run: terraform init

    - name: Terraform plan
      run: terraform plan -out=tfplan

    - name: Terraform apply
      run: terraform apply -auto-approve tfplan
      env:
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

  release:
    runs-on: ubuntu-latest
    needs: terraform
    steps:
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          terraform.tfstate
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
